### ISSUE TITLE
Hover effect on blog-logo is slightly off when you visit a Ghost "Page"

### ISSUE THREAD

**Issue by domculpa** [mityalebedev/The-Shell#23]
When you create a page in Ghost there is a problem when you visit it and hover over the blog-logo: the appearing red circle is off due to margin applied to top and bottom.

Corresponding CSS rule:

```css
.post-header #blog-logo::before {
    margin: 60px auto;
}
```

I fixed it manually in assets/css/screen.css to

```css
.post-header #blog-logo::before {
    margin: 0px auto;
}
```

There were three media queries for different screen sizes so I had to fix it on every appearance of the selector '.post-header #blog-logo:before'.

Wasn't sure if it's the right way to fix it, that's why there's no PR from me :sweat_smile: 

Thanks for your theme!
