### ISSUE TITLE
needs some updates for ghost version4

### ISSUE THREAD

**Issue by athamour1** [mityalebedev/The-Shell#45]
I liked very much this theme, so I tried to make small changes to be compatible with ghost 4, I saw 2 problems the logo of the site above the posts and the images from the posts.
I don't know if the following is right, but for me the following style, it worked.

```css

a#blog-logo {
  display: none!important;
}

figure>img {
  border: 0!important;
  object-fit: contain!important;
  height: auto!important;
}
```
